# Generated by Django 4.2.1 on 2023-06-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_profile_notes_note_author_alter_note_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('green', 'Зеленый'), ('red', 'Красный'), ('yellow', 'Желтый'), ('purple', 'Фиолетовый'), ('blue', 'Синий'), ('gray', 'Серый')], default='green', max_length=10, verbose_name='Цвет'),
        ),
    ]
